### ISSUE TITLE
Drive redirection does not work

### ISSUE THREAD

**Issue by lorenzoverbicaro** [scarygliders/X11RDP-o-Matic#57] opened 2016-01-26 21:57 UTC
I can´t redirect drives, even using the ./configure --enable-fuse command. I've tried all the branchs of neutrinolabs/xrdp, and installing in various Debian and Ubuntu distros. The clipboard files works perfectly in both ways, but the drive redirection looks simply does not exist, despite the thinclient_drive folder always appear. What can I be missing?

**Comment by metalefty** [comment] 2016-01-27 01:13
Duplicate of neutrinolabs/xrdp#308.

**Closed by metalefty** 2016-01-27 01:13 UTC
Labels: duplicate
